import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateFinoraDomainEntities1790145834818 implements MigrationInterface {
    name = 'CreateFinoraDomainEntities1790145834818'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."wallets_type_enum" AS ENUM('PERSONAL', 'SHARED')`);
        await queryRunner.query(`CREATE TABLE "wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "owner_id" uuid NOT NULL, "name" character varying(150) NOT NULL, "icon" character varying(255), "color" character varying(10), "description" text, "default_currency" character varying(10) NOT NULL DEFAULT 'VND', "type" "public"."wallets_type_enum" NOT NULL DEFAULT 'PERSONAL', "is_shared" boolean NOT NULL DEFAULT false, "is_archived" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1ba9a6e15c4a588af6233304ab" ON "wallets" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_acadc3471255d63d92f137ca2c" ON "wallets" ("name") `);
        await queryRunner.query(`CREATE TABLE "user_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" uuid NOT NULL, "default_currency" character varying(10) NOT NULL DEFAULT 'VND', "language" character varying(10) NOT NULL DEFAULT 'vi', "app_lock_enabled" boolean NOT NULL DEFAULT false, "pin_hash" character varying(255), "show_mascot" boolean NOT NULL DEFAULT true, "biometric_enabled" boolean NOT NULL DEFAULT false, "notification_preferences" jsonb, "default_transaction_visibility" character varying(50) NOT NULL DEFAULT 'PRIVATE', CONSTRAINT "UQ_4ed056b9344e6f7d8d46ec4b302" UNIQUE ("user_id"), CONSTRAINT "REL_4ed056b9344e6f7d8d46ec4b30" UNIQUE ("user_id"), CONSTRAINT "PK_00f004f5922a0744d174530d639" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4ed056b9344e6f7d8d46ec4b30" ON "user_settings" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "ai_personas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "tone_description" text, "system_prompt_snippet" text, "is_active" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_e0216e8fec1d47952f944ba865f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_16ed5ba70df272f06b6e1b0bd2" ON "ai_personas" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."wallet_members_role_enum" AS ENUM('OWNER', 'EDITOR', 'VIEWER')`);
        await queryRunner.query(`CREATE TABLE "wallet_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "wallet_id" uuid NOT NULL, "user_id" uuid NOT NULL, "role" "public"."wallet_members_role_enum" NOT NULL DEFAULT 'VIEWER', "joined_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_5bc259b22abf9ac9dd9fe881170" UNIQUE ("wallet_id", "user_id"), CONSTRAINT "PK_e57e7a4e9732e4caed055ca5d59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_46c372879098b7f813b37694b7" ON "wallet_members" ("wallet_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_23c6038fbb7a6166fa2f248bdc" ON "wallet_members" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "asset_tiers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "tier_name" character varying(100) NOT NULL, "min_net_worth" numeric(15,2) NOT NULL DEFAULT '0', "max_net_worth" numeric(15,2), "mascot_asset_url" character varying(500), "display_name" character varying(100) NOT NULL, "display_order" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_00bdbe77582b8aed95f7523e949" UNIQUE ("tier_name"), CONSTRAINT "PK_3a2697fa44ba9016c9586667783" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_00bdbe77582b8aed95f7523e94" ON "asset_tiers" ("tier_name") `);
        await queryRunner.query(`CREATE TYPE "public"."accounts_type_enum" AS ENUM('CASH', 'BANK_ACCOUNT', 'E_WALLET', 'CREDIT_CARD', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "wallet_id" uuid NOT NULL, "name" character varying(150) NOT NULL, "type" "public"."accounts_type_enum" NOT NULL DEFAULT 'CASH', "currency" character varying(10) NOT NULL DEFAULT 'VND', "balance" numeric(15,2) NOT NULL DEFAULT '0', "available_balance" numeric(15,2) NOT NULL DEFAULT '0', "account_number_last4" character varying(4), "bank_code" character varying(50), "color" character varying(10), "is_archived" boolean NOT NULL DEFAULT false, "exclude_from_net_worth" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_5a7a02c20412299d198e097a8fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b280f1f137807763a73d6d3dee" ON "accounts" ("wallet_id") `);
        await queryRunner.query(`CREATE TABLE "transfers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "from_account_id" uuid NOT NULL, "to_account_id" uuid NOT NULL, "created_by" uuid NOT NULL, "fee_account_id" uuid, "fee" numeric(15,2) NOT NULL DEFAULT '0', "from_amount" numeric(15,2) NOT NULL, "from_currency" character varying(10) NOT NULL DEFAULT 'VND', "to_amount" numeric(15,2) NOT NULL, "to_currency" character varying(10) NOT NULL DEFAULT 'VND', "exchange_rate" numeric(15,6) NOT NULL DEFAULT '1', "note" text, "transfer_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f712e908b465e0085b4408cabc3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_77a01df4f4cc8f5c87f9910385" ON "transfers" ("from_account_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e92aab332875987c4bd6ddc76" ON "transfers" ("to_account_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9820c7dff189cc9d50703fa162" ON "transfers" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_0aa5375bd4d9ed1f0342d9aeac" ON "transfers" ("fee_account_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_62d8d9260c98c3c34926855a3b" ON "transfers" ("transfer_date") `);
        await queryRunner.query(`CREATE TYPE "public"."categories_type_enum" AS ENUM('EXPENSE', 'INCOME', 'BOTH')`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" uuid, "parent_id" uuid, "name" character varying(100) NOT NULL, "type" "public"."categories_type_enum" NOT NULL DEFAULT 'EXPENSE', "color" character varying(10), "icon" character varying(255), "display_order" integer NOT NULL DEFAULT '0', "is_system" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2296b7fe012d95646fa41921c8" ON "categories" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_88cea2dc9c31951d06437879b4" ON "categories" ("parent_id") `);
        await queryRunner.query(`CREATE TABLE "receipts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "account_id" uuid NOT NULL, "image_url" character varying(500) NOT NULL, "merchant_name" character varying(200), "total_amount" numeric(15,2) NOT NULL DEFAULT '0', "tax_amount" numeric(15,2), "tip_amount" numeric(15,2), "ocr_raw_data" jsonb, "scanned_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5e8182d7c29e023da6e1ff33bfe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dbaaf3186f373127d47311dfc5" ON "receipts" ("account_id") `);
        await queryRunner.query(`CREATE TYPE "public"."transactions_type_enum" AS ENUM('EXPENSE', 'INCOME')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_source_enum" AS ENUM('MANUAL', 'CHAT_TEXT', 'VOICE', 'RECEIPT_SCAN', 'BANK_NOTIFICATION', 'RECURRING')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_status_enum" AS ENUM('PENDING_CONFIRMATION', 'CONFIRMED', 'REJECTED')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_visibility_enum" AS ENUM('PRIVATE', 'FRIENDS')`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "account_id" uuid NOT NULL, "created_by" uuid NOT NULL, "category_id" uuid NOT NULL, "receipt_id" uuid, "chat_message_id" uuid, "recurring_transaction_id" uuid, "type" "public"."transactions_type_enum" NOT NULL DEFAULT 'EXPENSE', "amount" numeric(15,2) NOT NULL DEFAULT '0', "currency" character varying(10) NOT NULL DEFAULT 'VND', "name" character varying(200) NOT NULL, "note" text, "source" "public"."transactions_source_enum" NOT NULL DEFAULT 'MANUAL', "status" "public"."transactions_status_enum" NOT NULL DEFAULT 'CONFIRMED', "visibility" "public"."transactions_visibility_enum" NOT NULL DEFAULT 'PRIVATE', "amount_hidden" boolean NOT NULL DEFAULT false, "is_recurring" boolean NOT NULL DEFAULT false, "fee" numeric(15,2) NOT NULL DEFAULT '0', "exclude_from_report" boolean NOT NULL DEFAULT false, "location_name" character varying(255), "latitude" numeric(10,7), "longitude" numeric(10,7), "transaction_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_49c0d6e8ba4bfb5582000d851f" ON "transactions" ("account_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_77e84561125adeccf287547f66" ON "transactions" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_c9e41213ca42d50132ed7ab2b0" ON "transactions" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_410675535f9abc658754a04072" ON "transactions" ("receipt_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a24e36d4374026709ab0179540" ON "transactions" ("chat_message_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_50371499043ce644481531ce05" ON "transactions" ("recurring_transaction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1727abfbb0b1dfd42c357b8c3" ON "transactions" ("transaction_date") `);
        await queryRunner.query(`CREATE TYPE "public"."transaction_photos_type_enum" AS ENUM('RECEIPT', 'MOMENT')`);
        await queryRunner.query(`CREATE TABLE "transaction_photos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "transaction_id" uuid NOT NULL, "photo_url" character varying(500) NOT NULL, "type" "public"."transaction_photos_type_enum" NOT NULL DEFAULT 'RECEIPT', "is_cover" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_eecb5daf6700c5a575bd5708f9b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d28c867ace91ec53878a9e0435" ON "transaction_photos" ("transaction_id") `);
        await queryRunner.query(`CREATE TABLE "receipt_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "receipt_id" uuid NOT NULL, "item_name" character varying(200) NOT NULL, "quantity" numeric(10,3) NOT NULL DEFAULT '1', "unit_price" numeric(15,2) NOT NULL DEFAULT '0', "total_price" numeric(15,2) NOT NULL DEFAULT '0', "category_id" uuid, CONSTRAINT "PK_8633ef98a0b970a980ebfd246e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9f35634152710322f029693840" ON "receipt_items" ("receipt_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b0c01805eb80d1dff5e379ba23" ON "receipt_items" ("category_id") `);
        await queryRunner.query(`CREATE TABLE "post_reactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "transaction_id" uuid NOT NULL, "user_id" uuid NOT NULL, "emoji" character varying(20) NOT NULL, CONSTRAINT "UQ_aeaae7753b54e798e3e51e27a8d" UNIQUE ("transaction_id", "user_id"), CONSTRAINT "PK_6decd1418b8f35995281eaa6e09" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6432222b696d5808e67941a1b7" ON "post_reactions" ("transaction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8268cd23ab20dcef2bfd3cbada" ON "post_reactions" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."friendships_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'BLOCKED')`);
        await queryRunner.query(`CREATE TABLE "friendships" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "requester_id" uuid NOT NULL, "addressee_id" uuid NOT NULL, "status" "public"."friendships_status_enum" NOT NULL DEFAULT 'PENDING', CONSTRAINT "UQ_2697f4d8948008ebd0784fe79c7" UNIQUE ("requester_id", "addressee_id"), CONSTRAINT "PK_08af97d0be72942681757f07bc8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4cf3c68ed4a5a9fde8d4c2b731" ON "friendships" ("requester_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_01b0760fd2402d21f12c6dc5f8" ON "friendships" ("addressee_id") `);
        await queryRunner.query(`CREATE TYPE "public"."direct_messages_type_enum" AS ENUM('TEXT', 'IMAGE', 'TRANSACTION_SHARE')`);
        await queryRunner.query(`CREATE TABLE "direct_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "sender_id" uuid NOT NULL, "receiver_id" uuid NOT NULL, "type" "public"."direct_messages_type_enum" NOT NULL DEFAULT 'TEXT', "content" text NOT NULL, "media_url" character varying(500), "reply_to_message_id" uuid, "related_transaction_id" uuid, "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP WITH TIME ZONE, "deleted_for_sender" boolean NOT NULL DEFAULT false, "deleted_for_receiver" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_8373c1bb93939978ef05ae650d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_867d7903affb6b677ca8567405" ON "direct_messages" ("sender_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_334926b8a9956b0dec331d960b" ON "direct_messages" ("receiver_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_23c6358da43135539a985631a8" ON "direct_messages" ("reply_to_message_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6cd2252bef3d785004d5881990" ON "direct_messages" ("related_transaction_id") `);
        await queryRunner.query(`CREATE TABLE "message_reactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "message_id" uuid NOT NULL, "user_id" uuid NOT NULL, "emoji" character varying(20) NOT NULL, CONSTRAINT "UQ_7aa2ff89b0f736fa785294739bb" UNIQUE ("message_id", "user_id"), CONSTRAINT "PK_654a9f0059ff93a8f156be66a5b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ce61e365d81a9dfc15cd36513b" ON "message_reactions" ("message_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b6d3eda2f99b64016d6a4cf112" ON "message_reactions" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."savings_goals_status_enum" AS ENUM('ACTIVE', 'COMPLETED', 'WITHDRAWN', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "savings_goals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "wallet_id" uuid NOT NULL, "account_id" uuid NOT NULL, "name" character varying(150) NOT NULL, "icon" character varying(255), "color" character varying(10), "is_favorite" boolean NOT NULL DEFAULT false, "target_amount" numeric(15,2) NOT NULL, "current_amount" numeric(15,2) NOT NULL DEFAULT '0', "target_date" TIMESTAMP WITH TIME ZONE, "status" "public"."savings_goals_status_enum" NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "PK_4f1e133521cfbf2b4252bd8f09d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d6e57126f43687d4c0e4530164" ON "savings_goals" ("wallet_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5941a3f79c2489fb3f5a253be7" ON "savings_goals" ("account_id") `);
        await queryRunner.query(`CREATE TABLE "savings_contributions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "goal_id" uuid NOT NULL, "account_id" uuid NOT NULL, "amount" numeric(15,2) NOT NULL, "note" text, "contribution_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2df255cb0de0da5d8e9c9d2a3a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5d6691cecbfc1fa95992285a3e" ON "savings_contributions" ("goal_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5a19abe5419aa09c7aae1c0af8" ON "savings_contributions" ("account_id") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('BUDGET_WARNING', 'BUDGET_EXCEEDED', 'RECURRING_EXECUTED', 'LOAN_DUE', 'LOAN_PAYMENT_RECEIVED', 'SAVINGS_GOAL_COMPLETED', 'SAVINGS_GOAL_MILESTONE', 'ASSET_TIER_UP', 'FRIEND_REQUEST', 'FRIEND_ACCEPTED', 'FRIEND_TRANSACTION_POSTED', 'POST_REACTED', 'NEW_DIRECT_MESSAGE', 'MESSAGE_REACTED', 'WALLET_INVITE', 'WALLET_MEMBER_CHANGED', 'SECURITY_ALERT')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" uuid NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying(200) NOT NULL, "body" text NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "related_entity_type" character varying(100), "related_entity_id" uuid, "metadata" jsonb, "action_url" character varying(500), "read_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9a8a82462cab47c73d25f49261" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1e465cab16c31698617e8f7c0d" ON "notifications" ("related_entity_id") `);
        await queryRunner.query(`CREATE TYPE "public"."recurring_transactions_type_enum" AS ENUM('EXPENSE', 'INCOME')`);
        await queryRunner.query(`CREATE TYPE "public"."recurring_transactions_frequency_enum" AS ENUM('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY')`);
        await queryRunner.query(`CREATE TABLE "recurring_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "wallet_id" uuid NOT NULL, "account_id" uuid NOT NULL, "category_id" uuid NOT NULL, "created_by" uuid NOT NULL, "name" character varying(200) NOT NULL, "amount" numeric(15,2) NOT NULL DEFAULT '0', "currency" character varying(10) NOT NULL DEFAULT 'VND', "type" "public"."recurring_transactions_type_enum" NOT NULL DEFAULT 'EXPENSE', "frequency" "public"."recurring_transactions_frequency_enum" NOT NULL DEFAULT 'MONTHLY', "start_date" TIMESTAMP WITH TIME ZONE NOT NULL, "end_date" TIMESTAMP WITH TIME ZONE, "next_run_date" TIMESTAMP WITH TIME ZONE NOT NULL, "is_paused" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_6485db3243762a54992dc0ce3b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8a74a7e3f7a4a3a0a57a48c042" ON "recurring_transactions" ("wallet_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_49ccbdbeef159c1c12b1931a5b" ON "recurring_transactions" ("account_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_eb623e5e626cf95fd42710adf2" ON "recurring_transactions" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c06044c4ea29df6ce73b09f8f2" ON "recurring_transactions" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_5812ae43cc8f3995e5a0906bcd" ON "recurring_transactions" ("next_run_date") `);
        await queryRunner.query(`CREATE TYPE "public"."loans_type_enum" AS ENUM('LENT', 'BORROWED', 'INSTALLMENT')`);
        await queryRunner.query(`CREATE TYPE "public"."loans_interest_period_enum" AS ENUM('YEARLY', 'MONTHLY')`);
        await queryRunner.query(`CREATE TYPE "public"."loans_status_enum" AS ENUM('ACTIVE', 'SETTLED', 'OVERDUE')`);
        await queryRunner.query(`CREATE TABLE "loans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "wallet_id" uuid NOT NULL, "account_id" uuid NOT NULL, "created_by" uuid NOT NULL, "type" "public"."loans_type_enum" NOT NULL DEFAULT 'LENT', "contact_name" character varying(150) NOT NULL, "contact_info" character varying(255), "principal_amount" numeric(15,2) NOT NULL, "remaining_amount" numeric(15,2) NOT NULL, "is_interest_bearing" boolean NOT NULL DEFAULT false, "interest_rate" numeric(5,2), "interest_period" "public"."loans_interest_period_enum", "currency" character varying(10) NOT NULL DEFAULT 'VND', "note" text, "loan_date" TIMESTAMP WITH TIME ZONE NOT NULL, "due_date" TIMESTAMP WITH TIME ZONE, "status" "public"."loans_status_enum" NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "PK_5c6942c1e13e4de135c5203ee61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cc7e613f77daa796ce966d6cae" ON "loans" ("wallet_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4ca248baa776dbc6864eb6747f" ON "loans" ("account_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c3b93ceba889c7bb9319d0b9e4" ON "loans" ("created_by") `);
        await queryRunner.query(`CREATE TABLE "loan_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "loan_id" uuid NOT NULL, "account_id" uuid NOT NULL, "amount" numeric(15,2) NOT NULL, "note" text, "payment_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_db75e38243b5f2cb9e728da4d0f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6584bab09ac53bd8d00d74a58c" ON "loan_payments" ("loan_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_76079e061d9b524cc9287fba09" ON "loan_payments" ("account_id") `);
        await queryRunner.query(`CREATE TYPE "public"."chat_messages_role_enum" AS ENUM('USER', 'ASSISTANT')`);
        await queryRunner.query(`CREATE TYPE "public"."chat_messages_message_type_enum" AS ENUM('TEXT', 'CHART', 'TRANSACTION_CONFIRMATION', 'REPORT')`);
        await queryRunner.query(`CREATE TABLE "chat_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" uuid NOT NULL, "wallet_id" uuid NOT NULL, "role" "public"."chat_messages_role_enum" NOT NULL DEFAULT 'USER', "message_type" "public"."chat_messages_message_type_enum" NOT NULL DEFAULT 'TEXT', "text_content" text NOT NULL, "payload_json" jsonb, CONSTRAINT "PK_40c55ee0e571e268b0d3cd37d10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5588b6cea298cedec7063c0d33" ON "chat_messages" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_089d3d7d740d6e5dee4a693878" ON "chat_messages" ("wallet_id") `);
        await queryRunner.query(`CREATE TYPE "public"."budgets_period_enum" AS ENUM('WEEKLY', 'MONTHLY')`);
        await queryRunner.query(`CREATE TABLE "budgets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "wallet_id" uuid NOT NULL, "category_id" uuid NOT NULL, "amount_limit" numeric(15,2) NOT NULL, "period" "public"."budgets_period_enum" NOT NULL DEFAULT 'MONTHLY', "used_amount" numeric(15,2) NOT NULL DEFAULT '0', "period_start" TIMESTAMP WITH TIME ZONE NOT NULL, "period_end" TIMESTAMP WITH TIME ZONE NOT NULL, "rollover_enabled" boolean NOT NULL DEFAULT false, "notify_threshold" integer NOT NULL DEFAULT '80', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_9c8a51748f82387644b773da482" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7f57b6f0516ef8c196d38743ad" ON "budgets" ("wallet_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4bb589bf6db49e8c1fd6af05f4" ON "budgets" ("category_id") `);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_1ba9a6e15c4a588af6233304ab0" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_settings" ADD CONSTRAINT "FK_4ed056b9344e6f7d8d46ec4b302" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_personas" ADD CONSTRAINT "FK_16ed5ba70df272f06b6e1b0bd2e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_members" ADD CONSTRAINT "FK_46c372879098b7f813b37694b71" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_members" ADD CONSTRAINT "FK_23c6038fbb7a6166fa2f248bdcd" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_b280f1f137807763a73d6d3dee1" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_77a01df4f4cc8f5c87f9910385b" FOREIGN KEY ("from_account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_6e92aab332875987c4bd6ddc763" FOREIGN KEY ("to_account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_9820c7dff189cc9d50703fa162c" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_0aa5375bd4d9ed1f0342d9aeace" FOREIGN KEY ("fee_account_id") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_2296b7fe012d95646fa41921c8b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_88cea2dc9c31951d06437879b40" FOREIGN KEY ("parent_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receipts" ADD CONSTRAINT "FK_dbaaf3186f373127d47311dfc54" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_49c0d6e8ba4bfb5582000d851f0" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_77e84561125adeccf287547f66e" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_c9e41213ca42d50132ed7ab2b0f" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_410675535f9abc658754a040724" FOREIGN KEY ("receipt_id") REFERENCES "receipts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_a24e36d4374026709ab0179540c" FOREIGN KEY ("chat_message_id") REFERENCES "chat_messages"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_50371499043ce644481531ce059" FOREIGN KEY ("recurring_transaction_id") REFERENCES "recurring_transactions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_photos" ADD CONSTRAINT "FK_d28c867ace91ec53878a9e0435d" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receipt_items" ADD CONSTRAINT "FK_9f35634152710322f0296938400" FOREIGN KEY ("receipt_id") REFERENCES "receipts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receipt_items" ADD CONSTRAINT "FK_b0c01805eb80d1dff5e379ba235" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_reactions" ADD CONSTRAINT "FK_6432222b696d5808e67941a1b78" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_reactions" ADD CONSTRAINT "FK_8268cd23ab20dcef2bfd3cbada0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friendships" ADD CONSTRAINT "FK_4cf3c68ed4a5a9fde8d4c2b7319" FOREIGN KEY ("requester_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friendships" ADD CONSTRAINT "FK_01b0760fd2402d21f12c6dc5f89" FOREIGN KEY ("addressee_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "direct_messages" ADD CONSTRAINT "FK_867d7903affb6b677ca85674050" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "direct_messages" ADD CONSTRAINT "FK_334926b8a9956b0dec331d960bd" FOREIGN KEY ("receiver_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "direct_messages" ADD CONSTRAINT "FK_23c6358da43135539a985631a8c" FOREIGN KEY ("reply_to_message_id") REFERENCES "direct_messages"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "direct_messages" ADD CONSTRAINT "FK_6cd2252bef3d785004d58819903" FOREIGN KEY ("related_transaction_id") REFERENCES "transactions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_reactions" ADD CONSTRAINT "FK_ce61e365d81a9dfc15cd36513b0" FOREIGN KEY ("message_id") REFERENCES "direct_messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_reactions" ADD CONSTRAINT "FK_b6d3eda2f99b64016d6a4cf112f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "savings_goals" ADD CONSTRAINT "FK_d6e57126f43687d4c0e4530164c" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "savings_goals" ADD CONSTRAINT "FK_5941a3f79c2489fb3f5a253be7c" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "savings_contributions" ADD CONSTRAINT "FK_5d6691cecbfc1fa95992285a3e4" FOREIGN KEY ("goal_id") REFERENCES "savings_goals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "savings_contributions" ADD CONSTRAINT "FK_5a19abe5419aa09c7aae1c0af85" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recurring_transactions" ADD CONSTRAINT "FK_8a74a7e3f7a4a3a0a57a48c042e" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recurring_transactions" ADD CONSTRAINT "FK_49ccbdbeef159c1c12b1931a5b7" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recurring_transactions" ADD CONSTRAINT "FK_eb623e5e626cf95fd42710adf25" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recurring_transactions" ADD CONSTRAINT "FK_c06044c4ea29df6ce73b09f8f28" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_cc7e613f77daa796ce966d6cae7" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_4ca248baa776dbc6864eb6747f5" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_c3b93ceba889c7bb9319d0b9e41" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_payments" ADD CONSTRAINT "FK_6584bab09ac53bd8d00d74a58cd" FOREIGN KEY ("loan_id") REFERENCES "loans"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_payments" ADD CONSTRAINT "FK_76079e061d9b524cc9287fba095" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_5588b6cea298cedec7063c0d33e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_089d3d7d740d6e5dee4a693878e" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "FK_7f57b6f0516ef8c196d38743adb" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "FK_4bb589bf6db49e8c1fd6af05f49" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "FK_4bb589bf6db49e8c1fd6af05f49"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "FK_7f57b6f0516ef8c196d38743adb"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_089d3d7d740d6e5dee4a693878e"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_5588b6cea298cedec7063c0d33e"`);
        await queryRunner.query(`ALTER TABLE "loan_payments" DROP CONSTRAINT "FK_76079e061d9b524cc9287fba095"`);
        await queryRunner.query(`ALTER TABLE "loan_payments" DROP CONSTRAINT "FK_6584bab09ac53bd8d00d74a58cd"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_c3b93ceba889c7bb9319d0b9e41"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_4ca248baa776dbc6864eb6747f5"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_cc7e613f77daa796ce966d6cae7"`);
        await queryRunner.query(`ALTER TABLE "recurring_transactions" DROP CONSTRAINT "FK_c06044c4ea29df6ce73b09f8f28"`);
        await queryRunner.query(`ALTER TABLE "recurring_transactions" DROP CONSTRAINT "FK_eb623e5e626cf95fd42710adf25"`);
        await queryRunner.query(`ALTER TABLE "recurring_transactions" DROP CONSTRAINT "FK_49ccbdbeef159c1c12b1931a5b7"`);
        await queryRunner.query(`ALTER TABLE "recurring_transactions" DROP CONSTRAINT "FK_8a74a7e3f7a4a3a0a57a48c042e"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "savings_contributions" DROP CONSTRAINT "FK_5a19abe5419aa09c7aae1c0af85"`);
        await queryRunner.query(`ALTER TABLE "savings_contributions" DROP CONSTRAINT "FK_5d6691cecbfc1fa95992285a3e4"`);
        await queryRunner.query(`ALTER TABLE "savings_goals" DROP CONSTRAINT "FK_5941a3f79c2489fb3f5a253be7c"`);
        await queryRunner.query(`ALTER TABLE "savings_goals" DROP CONSTRAINT "FK_d6e57126f43687d4c0e4530164c"`);
        await queryRunner.query(`ALTER TABLE "message_reactions" DROP CONSTRAINT "FK_b6d3eda2f99b64016d6a4cf112f"`);
        await queryRunner.query(`ALTER TABLE "message_reactions" DROP CONSTRAINT "FK_ce61e365d81a9dfc15cd36513b0"`);
        await queryRunner.query(`ALTER TABLE "direct_messages" DROP CONSTRAINT "FK_6cd2252bef3d785004d58819903"`);
        await queryRunner.query(`ALTER TABLE "direct_messages" DROP CONSTRAINT "FK_23c6358da43135539a985631a8c"`);
        await queryRunner.query(`ALTER TABLE "direct_messages" DROP CONSTRAINT "FK_334926b8a9956b0dec331d960bd"`);
        await queryRunner.query(`ALTER TABLE "direct_messages" DROP CONSTRAINT "FK_867d7903affb6b677ca85674050"`);
        await queryRunner.query(`ALTER TABLE "friendships" DROP CONSTRAINT "FK_01b0760fd2402d21f12c6dc5f89"`);
        await queryRunner.query(`ALTER TABLE "friendships" DROP CONSTRAINT "FK_4cf3c68ed4a5a9fde8d4c2b7319"`);
        await queryRunner.query(`ALTER TABLE "post_reactions" DROP CONSTRAINT "FK_8268cd23ab20dcef2bfd3cbada0"`);
        await queryRunner.query(`ALTER TABLE "post_reactions" DROP CONSTRAINT "FK_6432222b696d5808e67941a1b78"`);
        await queryRunner.query(`ALTER TABLE "receipt_items" DROP CONSTRAINT "FK_b0c01805eb80d1dff5e379ba235"`);
        await queryRunner.query(`ALTER TABLE "receipt_items" DROP CONSTRAINT "FK_9f35634152710322f0296938400"`);
        await queryRunner.query(`ALTER TABLE "transaction_photos" DROP CONSTRAINT "FK_d28c867ace91ec53878a9e0435d"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_50371499043ce644481531ce059"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_a24e36d4374026709ab0179540c"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_410675535f9abc658754a040724"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_c9e41213ca42d50132ed7ab2b0f"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_77e84561125adeccf287547f66e"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_49c0d6e8ba4bfb5582000d851f0"`);
        await queryRunner.query(`ALTER TABLE "receipts" DROP CONSTRAINT "FK_dbaaf3186f373127d47311dfc54"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_88cea2dc9c31951d06437879b40"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_2296b7fe012d95646fa41921c8b"`);
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_0aa5375bd4d9ed1f0342d9aeace"`);
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_9820c7dff189cc9d50703fa162c"`);
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_6e92aab332875987c4bd6ddc763"`);
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_77a01df4f4cc8f5c87f9910385b"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_b280f1f137807763a73d6d3dee1"`);
        await queryRunner.query(`ALTER TABLE "wallet_members" DROP CONSTRAINT "FK_23c6038fbb7a6166fa2f248bdcd"`);
        await queryRunner.query(`ALTER TABLE "wallet_members" DROP CONSTRAINT "FK_46c372879098b7f813b37694b71"`);
        await queryRunner.query(`ALTER TABLE "ai_personas" DROP CONSTRAINT "FK_16ed5ba70df272f06b6e1b0bd2e"`);
        await queryRunner.query(`ALTER TABLE "user_settings" DROP CONSTRAINT "FK_4ed056b9344e6f7d8d46ec4b302"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_1ba9a6e15c4a588af6233304ab0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4bb589bf6db49e8c1fd6af05f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f57b6f0516ef8c196d38743ad"`);
        await queryRunner.query(`DROP TABLE "budgets"`);
        await queryRunner.query(`DROP TYPE "public"."budgets_period_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_089d3d7d740d6e5dee4a693878"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5588b6cea298cedec7063c0d33"`);
        await queryRunner.query(`DROP TABLE "chat_messages"`);
        await queryRunner.query(`DROP TYPE "public"."chat_messages_message_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."chat_messages_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76079e061d9b524cc9287fba09"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6584bab09ac53bd8d00d74a58c"`);
        await queryRunner.query(`DROP TABLE "loan_payments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3b93ceba889c7bb9319d0b9e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ca248baa776dbc6864eb6747f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc7e613f77daa796ce966d6cae"`);
        await queryRunner.query(`DROP TABLE "loans"`);
        await queryRunner.query(`DROP TYPE "public"."loans_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."loans_interest_period_enum"`);
        await queryRunner.query(`DROP TYPE "public"."loans_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5812ae43cc8f3995e5a0906bcd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c06044c4ea29df6ce73b09f8f2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb623e5e626cf95fd42710adf2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_49ccbdbeef159c1c12b1931a5b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a74a7e3f7a4a3a0a57a48c042"`);
        await queryRunner.query(`DROP TABLE "recurring_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."recurring_transactions_frequency_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recurring_transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e465cab16c31698617e8f7c0d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a8a82462cab47c73d25f49261"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a19abe5419aa09c7aae1c0af8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d6691cecbfc1fa95992285a3e"`);
        await queryRunner.query(`DROP TABLE "savings_contributions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5941a3f79c2489fb3f5a253be7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6e57126f43687d4c0e4530164"`);
        await queryRunner.query(`DROP TABLE "savings_goals"`);
        await queryRunner.query(`DROP TYPE "public"."savings_goals_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6d3eda2f99b64016d6a4cf112"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce61e365d81a9dfc15cd36513b"`);
        await queryRunner.query(`DROP TABLE "message_reactions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6cd2252bef3d785004d5881990"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23c6358da43135539a985631a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_334926b8a9956b0dec331d960b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_867d7903affb6b677ca8567405"`);
        await queryRunner.query(`DROP TABLE "direct_messages"`);
        await queryRunner.query(`DROP TYPE "public"."direct_messages_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01b0760fd2402d21f12c6dc5f8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4cf3c68ed4a5a9fde8d4c2b731"`);
        await queryRunner.query(`DROP TABLE "friendships"`);
        await queryRunner.query(`DROP TYPE "public"."friendships_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8268cd23ab20dcef2bfd3cbada"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6432222b696d5808e67941a1b7"`);
        await queryRunner.query(`DROP TABLE "post_reactions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0c01805eb80d1dff5e379ba23"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f35634152710322f029693840"`);
        await queryRunner.query(`DROP TABLE "receipt_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d28c867ace91ec53878a9e0435"`);
        await queryRunner.query(`DROP TABLE "transaction_photos"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_photos_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1727abfbb0b1dfd42c357b8c3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50371499043ce644481531ce05"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a24e36d4374026709ab0179540"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_410675535f9abc658754a04072"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9e41213ca42d50132ed7ab2b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77e84561125adeccf287547f66"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_49c0d6e8ba4bfb5582000d851f"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_visibility_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dbaaf3186f373127d47311dfc5"`);
        await queryRunner.query(`DROP TABLE "receipts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88cea2dc9c31951d06437879b4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2296b7fe012d95646fa41921c8"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TYPE "public"."categories_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_62d8d9260c98c3c34926855a3b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0aa5375bd4d9ed1f0342d9aeac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9820c7dff189cc9d50703fa162"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e92aab332875987c4bd6ddc76"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77a01df4f4cc8f5c87f9910385"`);
        await queryRunner.query(`DROP TABLE "transfers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b280f1f137807763a73d6d3dee"`);
        await queryRunner.query(`DROP TABLE "accounts"`);
        await queryRunner.query(`DROP TYPE "public"."accounts_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_00bdbe77582b8aed95f7523e94"`);
        await queryRunner.query(`DROP TABLE "asset_tiers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23c6038fbb7a6166fa2f248bdc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_46c372879098b7f813b37694b7"`);
        await queryRunner.query(`DROP TABLE "wallet_members"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_members_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_16ed5ba70df272f06b6e1b0bd2"`);
        await queryRunner.query(`DROP TABLE "ai_personas"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ed056b9344e6f7d8d46ec4b30"`);
        await queryRunner.query(`DROP TABLE "user_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_acadc3471255d63d92f137ca2c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ba9a6e15c4a588af6233304ab"`);
        await queryRunner.query(`DROP TABLE "wallets"`);
        await queryRunner.query(`DROP TYPE "public"."wallets_type_enum"`);
    }

}
