export const SYSTEM_PERMISSIONS = {
  // Users Management
  USERS_CREATE: 'USERS_CREATE',
  USERS_READ: 'USERS_READ',
  USERS_UPDATE: 'USERS_UPDATE',
  USERS_DELETE: 'USERS_DELETE',
  USERS_ASSIGN_ROLE: 'USERS_ASSIGN_ROLE',

  // Roles Management
  ROLES_CREATE: 'ROLES_CREATE',
  ROLES_READ: 'ROLES_READ',
  ROLES_UPDATE: 'ROLES_UPDATE',
  ROLES_DELETE: 'ROLES_DELETE',
  ROLES_ASSIGN_PERMISSION: 'ROLES_ASSIGN_PERMISSION',

  // Permissions Management
  PERMISSIONS_CREATE: 'PERMISSIONS_CREATE',
  PERMISSIONS_READ: 'PERMISSIONS_READ',
  PERMISSIONS_UPDATE: 'PERMISSIONS_UPDATE',
  PERMISSIONS_DELETE: 'PERMISSIONS_DELETE',

  // Groups Management
  GROUPS_CREATE: 'GROUPS_CREATE',
  GROUPS_READ: 'GROUPS_READ',
  GROUPS_UPDATE: 'GROUPS_UPDATE',
  GROUPS_DELETE: 'GROUPS_DELETE',
  GROUPS_TRANSFER_OWNERSHIP: 'GROUPS_TRANSFER_OWNERSHIP',
  GROUPS_MEMBER_INVITE: 'GROUPS_MEMBER_INVITE',
  GROUPS_MEMBER_ASSIGN_ROLE: 'GROUPS_MEMBER_ASSIGN_ROLE',
  GROUPS_MEMBER_KICK: 'GROUPS_MEMBER_KICK',

  // System Management
  SYSTEM_CONFIG_READ: 'SYSTEM_CONFIG_READ',
  SYSTEM_CONFIG_UPDATE: 'SYSTEM_CONFIG_UPDATE',
  SYSTEM_AUDIT_VIEW: 'SYSTEM_AUDIT_VIEW',
} as const;

export type SystemPermission =
  (typeof SYSTEM_PERMISSIONS)[keyof typeof SYSTEM_PERMISSIONS];

export const ADMIN_EXCLUSIVE_PERMISSIONS: string[] = [
  SYSTEM_PERMISSIONS.USERS_CREATE,
  SYSTEM_PERMISSIONS.USERS_READ,
  SYSTEM_PERMISSIONS.USERS_UPDATE,
  SYSTEM_PERMISSIONS.USERS_DELETE,
  SYSTEM_PERMISSIONS.USERS_ASSIGN_ROLE,
  SYSTEM_PERMISSIONS.ROLES_CREATE,
  SYSTEM_PERMISSIONS.ROLES_READ,
  SYSTEM_PERMISSIONS.ROLES_UPDATE,
  SYSTEM_PERMISSIONS.ROLES_DELETE,
  SYSTEM_PERMISSIONS.ROLES_ASSIGN_PERMISSION,
  SYSTEM_PERMISSIONS.PERMISSIONS_CREATE,
  SYSTEM_PERMISSIONS.PERMISSIONS_READ,
  SYSTEM_PERMISSIONS.PERMISSIONS_UPDATE,
  SYSTEM_PERMISSIONS.PERMISSIONS_DELETE,
  SYSTEM_PERMISSIONS.SYSTEM_CONFIG_READ,
  SYSTEM_PERMISSIONS.SYSTEM_CONFIG_UPDATE,
  SYSTEM_PERMISSIONS.SYSTEM_AUDIT_VIEW,
];
