export enum TransactionSource {
  MANUAL = 'MANUAL',
  CHAT_TEXT = 'CHAT_TEXT',
  VOICE = 'VOICE',
  RECEIPT_SCAN = 'RECEIPT_SCAN',
  BANK_NOTIFICATION = 'BANK_NOTIFICATION',
  RECURRING = 'RECURRING',
}
